H=rgb2gray(imread('imglib1/apple1.jpg'));
subplot(3,2,1);
imshow(H);
title('Original Image');
subplot(3,2,2);
imhist(H);
title('Histogram');
subplot(3,2,3);
H1=adapthisteq(H);
imshow(H1);
title('Adapthisteq Graph');
subplot(3,2,4);
imhist(H1);
title('Adapthisteq Instogram');
subplot(3,2,5);
H2=histeq(H);
imshow(H2);
title('Histeq Instogram');
subplot(3,2,6);
imhist(H1);
title('Histeq Instogram');
